from typing import Literal
from pydantic import BaseModel, Field, ConfigDict


class AnalyzeRequest(BaseModel):
    """The incoming request payload from a user."""
    model_config = ConfigDict(extra="forbid")

    idea: str = Field(
        min_length=10,
        max_length=2000,
        description=(
            "The product idea to analyze. "
            "Must be at least 10 characters."
        )
    )


class Competitor(BaseModel):
    """A single competitor in the market."""
    name: str = Field(description="Name of the competitor")
    description: str = Field(description="Brief description of what they do")
    differentiator: str | None = Field(
        None,
        description="What makes them different or better"
    )


class FeasibilityReport(BaseModel):
    """The final structured report generated by the agents."""
    model_config = ConfigDict(extra="forbid")

    idea: str = Field(description="The original idea")
    market_overview: str = Field(
        description="A high-level summary of the market and demand"
    )
    competitors: list[Competitor] = Field(
        description="List of identified competitors"
    )
    opportunities: list[str] = Field(
        description="List of market opportunities or tailwinds"
    )
    gaps: list[str] = Field(
        description="List of missing features or gaps in the current market"
    )
    technical_feasibility: str = Field(
        description="Assessment of technical difficulty and required stack"
    )
    risks: list[str] = Field(
        description="List of potential risks (technical, market, etc.)"
    )
    recommendation: Literal["build", "dont_build", "build_with_caveats"] = \
        Field(description="The final binary/ternary recommendation")
    confidence: float = Field(
        ge=0,
        le=1,
        description="Confidence score from 0.0 to 1.0"
    )
    reasoning: str = Field(
        description="The deep reasoning behind the recommendation"
    )
    mvp_suggestion: str | None = Field(
        None,
        description="Suggested Minimum Viable Product to validate the idea"
    )
    engine: Literal["mock", "crew"] = Field(
        description=(
            "Indicates whether this report was generated by the "
            "mock fallback or the real LLM crew"
        )
    )


class AnalyzeResponse(BaseModel):
    """The outgoing HTTP response wrapping the report."""
    report: FeasibilityReport
    meta: dict = Field(
        default_factory=dict,
        description="Metadata like duration_ms or model used"
    )
